name: Update stats

on:
  schedule:
    # Runs at 00:05am CST
    - cron: '5 8 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: Arronlong
          # 目前为止的代码行
          SHOW_LINES_OF_CODE: True
          # 提交统计信息
          SHOW_COMMIT: True          
          # 您使用的编码语言
          SHOW_LANGUAGE: True
          # 不同年份的不同季度中编写的代码行
          SHOW_LOC_CHART: True
          # 用户的简短有趣事实信息
          SHOW_SHORT_INFO: True
          
          # 操作系统详细信息
          SHOW_OS: True
          # 已处理的项目
          SHOW_PROJECTS: True
          # “个人档案”浏览数
          SHOW_PROFILE_VIEWS: True
          # 代码编辑器列表
          SHOW_EDITORS: True
          # 您所在的时区
          SHOW_TIMEZONE: True
          # 周一~周日的提交数
          SHOW_DAYS_OF_WEEK: True
